### ISSUE TITLE
[2.x] Compile list of uses in `Pest.php` file

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest-plugin-drift#10]
Ideally, would be cool to have the list of `uses` compiled to the `Pest.php` file. I've just moved to the `--drift`plugin, the initialization of the test suite. So, if there is no `Pest.php` file, the `--drift`plugin will create it.

Now, when migrating a bunch of PHPUnit files, would be interesting to have their respective uses being compiled an written down to the `Pest.php` file. Here is an example:

```php
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic test example.
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

Result:
```php
<?php

test('the application returns a successful response', function () {
    $response = $this->get('/');

    $response->assertStatus(200);
});
```

```php
<?php // Pest.php

uses(TestCase::class, RefreshDatabase::class)->in('Feature');
```

I understand that this can be difficult, so if you want, you can close this issue for now.

**Comment by tomb1n0** [comment]
I think this would be really nice, this is definitely my preferred approach as it reduces the amount of boiler-plate in your actual test files.

Might be pretty tricky to implement though? If you had tests extending different TestCases in a directory, i guess the majority use case would win in `Pest.php`, and then the minority use inline `uses()`? 

This is of course assuming that an inline `uses()` referncing a TestCase will override the one in `Pest.php` - i can't remember if this works 🤔
