### ISSUE TITLE
Any plans to support converting PHPUnit #[Test] Attributes?

### ISSUE THREAD

**Issue by GeniJaho** [pestphp/pest-plugin-drift#23]
Hello guys,

I was using the Drift plugin on a project that had tests like these:

```php
#[Test]
public function a_user_may_not_change_their_email()
{}
 ```
 
 It doesn't work in this case. Are there any plans to convert Attributes as well? I would be happy to open a PR for them.
 Thank you 😁

**Comment by mandisma** [comment]
Hey,

We've got attribute conversion in the pipeline. No need for a PR this time. Thanks for bringing this up !

It will be available soon.

**Comment by GeniJaho** [comment]
That's fantastic, thank you so much ✌️
