### ISSUE TITLE
Does not support nikic/php-parser v5

### ISSUE THREAD

**Issue by carestad** [pestphp/pest-plugin-drift#42]
Hi

I wanted to give Pest a go and had a look at the [documentation for migrating from PHPUnit](https://pestphp.com/docs/migrating-from-phpunit-guide).

Unfortunately, I was not able to install the dependency due to it only supporting `nikic/php-parser` v4. Most other dependencies I have that rely on `nikic/php-parser` seem to support both v4 and v5 - is that possible here as well?

**Comment by Gompje** [comment]
you probably have the same packages as I had:

```
develop $ composer why nikic/php-parser                                                                                                                                                                                                                               ~/Herd/multipass-rocks
barryvdh/laravel-ide-helper         v2.15.1 requires nikic/php-parser (^4.18 || ^5)       
phpunit/php-code-coverage           10.1.11 requires nikic/php-parser (^4.18 || ^5.0)     
psy/psysh                           v0.12.0 requires nikic/php-parser (^5.0 || ^4.0)      
sebastian/complexity                3.2.0   requires nikic/php-parser (^4.18 || ^5.0)     
sebastian/lines-of-code             2.0.2   requires nikic/php-parser (^4.18 || ^5.0)     
ta-tikoma/phpunit-architecture-test 0.8.4   requires nikic/php-parser (^4.18.0 || ^5.0.0) 
```

Given they work with both versions, and this one does not; I simply added `"nikic/php-parser": "^4.18"` to my composer dev section to lock this package to this version. 

This allowed me to install the excellent plugin - and it migrated 92 old phpunit test files to pest 🙇‍♀️ 
🙏 a lot for this package! it save me a lot of time and allows me to prune double config settings

oh! given I don't need this package anymore, I just removed the fixed version and the package from composer. this reverted the package back to v5.0

**Comment by jonathanpmartins** [comment]
It's a bit inconvenient to have to install another package just for this functionality. It becomes even more inconvenient when the installation process don't work automatically and is a little hacky. Perhaps integrating this hole package directly into the PEST core is a better approach!

**Comment by lloricode** [comment]
you can run `composer require pestphp/pest-plugin-drift --dev --with-all-dependencies`, this will successfully install drift, 
after that you can run `./vendor/bin/pest --drift`,

then is drift successfully upgrade you test suits to pest syntax, you can safely remove `pestphp/pest-plugin-drift`, then bring back `nikic/php-parser` to your desire needed version

**Comment by mandisma** [comment]
The dependencies have been updated and now support nikic/php-parser v5
